--show con_name;

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER nva IDENTIFIED BY 123456;

GRANT CONNECT, DBA TO nva;

GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO nva;

GRANT UNLIMITED TABLESPACE TO nva;

--GRANT CREATE TABLE TO nva;

--AMERICAN_AMERICA.WE8MSWIN1252

alter session set container=pdbdb12c;
alter session set "_ORACLE_SCRIPT"=true;

CREATE USER nvc IDENTIFIED BY 123456 DEFAULT COLLATION BINARY_AI;

GRANT CONNECT, DBA TO nvc;

GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO nvc;

GRANT UNLIMITED TABLESPACE TO nvc;