--show con_name;

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER nva IDENTIFIED BY 123456;

GRANT CONNECT, DBA TO nva;

GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO nva;

GRANT UNLIMITED TABLESPACE TO nva;

--GRANT CREATE TABLE TO nva;

--AMERICAN_AMERICA.WE8MSWIN1252