/*
DROP TABLE ChiTietHD;
DROP TABLE HoaDon;
DROP TABLE TrangThai;
DROP TABLE NhanVien;
DROP TABLE PhanQuyen;
DROP TABLE KhachHang;
DROP TABLE HangHoa;
DROP TABLE NhaCungCap;
DROP TABLE Loai;
*/

CREATE TABLE Loai(
  MaLoai VARCHAR2(10) NOT NULL,
  GioiTinh NUMBER(1) NOT NULL,
  TenLoai NVARCHAR2(30) NOT NULL,
  CONSTRAINT pk_loai PRIMARY KEY (MaLoai)
);


CREATE TABLE NhaCungCap(
  MaNCC VARCHAR2(10) NOT NULL,
  TenCongTy NVARCHAR2(50) NOT NULL,
  Email VARCHAR2(50) NOT NULL,
  DienThoai VARCHAR2(24) NOT NULL,
  DiaChi NVARCHAR2(60) NOT NULL,
  CONSTRAINT pk_ncc PRIMARY KEY (MaNCC)
);


CREATE TABLE HangHoa (
  MaHH NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  TenHH NVARCHAR2(60) NOT NULL,
  MaLoai VARCHAR2(10) NOT NULL,
  Hinh NVARCHAR2(60),
  DonGia FLOAT NOT NULL,
  GiamGia FLOAT NOT NULL,
  MoTa NVARCHAR2(1000),
  MaNCC VARCHAR2(10) NOT NULL,
  CONSTRAINT pk_hh PRIMARY KEY (MaHH),
  CONSTRAINT fk_hh_loai FOREIGN KEY (MaLoai) REFERENCES Loai(MaLoai),
  CONSTRAINT fk_hh_ncc FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

ALTER TABLE HangHoa MODIFY MaHH GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 73 INCREMENT BY 1;

CREATE TABLE SanPhamKho (
  MaSP_Kho NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  MaHH NUMBER(10) NOT NULL,
  KichCo VARCHAR2(10) NULL,
  SoLuong NUMBER(10) NULL,
  CONSTRAINT pk_masp_kho PRIMARY KEY (MaSP_Kho),
  CONSTRAINT fk_spk_hh FOREIGN KEY (MaHH) REFERENCES HangHoa(MaHH)
);

ALTER TABLE SanPhamKho MODIFY MaSP_Kho GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 178 INCREMENT BY 1;

CREATE TABLE KhachHang (
  MaKH NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  MatKhau VARCHAR2(50) NOT NULL,
  HoTen NVARCHAR2(50) NOT NULL,
  DiaChi NVARCHAR2(60),
  DienThoai VARCHAR2(24),
  Email VARCHAR2(50) NOT NULL,
  Hinh VARCHAR2(50),
  TaiKhoan VARCHAR2(30),
  GioiTinh NVARCHAR2(50),
  NgaySinh DATE,
  TrangThaiHD NUMBER(1),
  CONSTRAINT pk_kh PRIMARY KEY (MaKH)
);

ALTER TABLE KhachHang MODIFY MatKhau VARCHAR2(50) NULL;
ALTER TABLE KhachHang MODIFY MaKH GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 12 INCREMENT BY 1;

CREATE TABLE PhanQuyen(
  MaPQ NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  Them NUMBER(1) NOT NULL,
  Sua NUMBER(1) NOT NULL,
  Xoa NUMBER(1) NOT NULL,
  Xem NUMBER(1) NOT NULL,
  CONSTRAINT pk_pq PRIMARY KEY (MaPQ)
);

ALTER TABLE PhanQuyen MODIFY MaPQ GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2 INCREMENT BY 1;

CREATE TABLE NhanVien (
  MaNV NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  HoTen NVARCHAR2(50) NOT NULL,
  Email VARCHAR2(50) NOT NULL,
  MatKhau VARCHAR2(50) NOT NULL,
  MaPQ NUMBER(10) NOT NULL,
  TrangThaiHD NUMBER(1),
  CONSTRAINT pk_nv PRIMARY KEY (MaNV),
  CONSTRAINT fk_nv_pq FOREIGN KEY (MaPQ) REFERENCES PhanQuyen(MaPQ)
);

ALTER TABLE PhanQuyen MODIFY MaPQ GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2 INCREMENT BY 1;

CREATE TABLE TrangThai(
  MaTrangThai NUMBER(10) NOT NULL,
  TenTrangThai NVARCHAR2(30) NOT NULL,
  CONSTRAINT pk_tt PRIMARY KEY (MaTrangThai)
);

CREATE TABLE HoaDon (
  MaHD NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  MaKH NUMBER(10) NOT NULL,
  NgayDat DATE NOT NULL,
  NgayGiao DATE,
  HoTen NVARCHAR2(50),
  DiaChi NVARCHAR2(60) NOT NULL,
  SDT_nguoinhan VARCHAR2(20),
  GhiChu NVARCHAR2(50),
  PhiVanChuyen NUMBER(9) NOT NULL,
  MaTrangThai NUMBER(10),
  MaNV NUMBER(10),
  TongTienHang FLOAT,
  TongThucThu FLOAT,
  CONSTRAINT pk_hd PRIMARY KEY (MaHD),
  CONSTRAINT fk_hd_kh FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
  CONSTRAINT fk_hd_tt FOREIGN KEY (MaTrangThai) REFERENCES TrangThai(MaTrangThai)
);

ALTER TABLE HoaDon MODIFY MaHD GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 23 INCREMENT BY 1;

CREATE TABLE ChiTietHD(
  MaCT NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  MaHD NUMBER(10) NOT NULL,
  MaHH NUMBER(10) NOT NULL,
  DonGia NUMBER(10,1) NOT NULL,
  GiamGia NUMBER(10,1) NULL,
  SoLuong NUMBER(10) NOT NULL,
  KichCo VARCHAR2(5),
  CONSTRAINT pk_cthd PRIMARY KEY (MaCT),
  CONSTRAINT fk_cthd_hd FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
  CONSTRAINT fk_cthd_hh FOREIGN KEY (MaHH) REFERENCES HangHoa(MaHH)
);

ALTER TABLE ChiTietHD MODIFY MaCT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 33 INCREMENT BY 1;

insert all
into PhanQuyen (MaPQ, Them, Sua, Xoa, Xem) values  (1, 1, 1, 1, 1)

into NhanVien (MaNV, HoTen, Email, MatKhau, MaPQ, TrangThaiHD) values (1, N'Admin', N'nv1@gmail.com', N'c4ca4238a0b923820dcc509a6f75849b', 1, 1)

into KhachHang (MaKH, MatKhau, HoTen, DiaChi, DienThoai, Email, Hinh, TaiKhoan, GioiTinh, NgaySinh, TrangThaiHD) values (4, N'c4ca4238a0b923820dcc509a6f75849b', N'Nguyễn Thanh Sang', N'Bình Dương', N'0971890712', N'sanglun2254@gmail.com', N'34441.png', N'sangnt2', N'Nam', NULL, 1)
into KhachHang (MaKH, MatKhau, HoTen, DiaChi, DienThoai, Email, Hinh, TaiKhoan, GioiTinh, NgaySinh, TrangThaiHD) values (5, N'c4ca4238a0b923820dcc509a6f75849b', N'Minh Cao', N'TPHCM', N'0971890712', N'minhcd@gmail.com', N'backg.jpg', N'minhcd', N'Nam', NULL, 1)
into KhachHang (MaKH, MatKhau, HoTen, DiaChi, DienThoai, Email, Hinh, TaiKhoan, GioiTinh, NgaySinh, TrangThaiHD) values (6, N'c4ca4238a0b923820dcc509a6f75849b', N'Nguyễn Thanh Sang', N'Bình Dương', N'0971890712', N'sanglun2254_1@gmail.com', N'long.jpg', N'sangnt', N'Nam', NULL, 1)
into KhachHang (MaKH, MatKhau, HoTen, DiaChi, DienThoai, Email, Hinh, TaiKhoan, GioiTinh, NgaySinh, TrangThaiHD) values (10, N'c4ca4238a0b923820dcc509a6f75849b', N'anonymouse', N'Không có', N'', N'pinkwater98@gmail.com', N'anonymouse.jpg', N'shanm', N'Nam', NULL, 1)
into KhachHang (MaKH, MatKhau, HoTen, DiaChi, DienThoai, Email, Hinh, TaiKhoan, GioiTinh, NgaySinh, TrangThaiHD) values (11, N'c4ca4238a0b923820dcc509a6f75849b', N'Đỗ Phúc Hậu', N'280 ADV', N'0904877306', N'wanriky2998@gmail.com', NULL, N'haudp', N'Nam', NULL, 1)

into NhaCungCap (MaNCC, TenCongTy, Email, DienThoai, DiaChi) values (N'ESHOP', N'ESHOP', N'eshop@gmail.com', N'1654651326', N'TPHCM')
into NhaCungCap (MaNCC, TenCongTy, Email, DienThoai, DiaChi) values (N'KENTA', N'KENTA', N'kenta@gmail.com', N'653256565', N'TPHCM')
into NhaCungCap (MaNCC, TenCongTy, Email, DienThoai, DiaChi) values (N'SENDO', N'SENDO', N'sendo@gmail.com', N'2356562323', N'TPHCM')
into NhaCungCap (MaNCC, TenCongTy, Email, DienThoai, DiaChi) values (N'YAME', N'YAME', N'yame@gmail.com', N'32565365323', N'BÌNH DƯƠNG')

into Loai (MaLoai, GioiTinh, TenLoai) values (N'ESAO001', 0, N'ÁO SƠ MI TAY DÀI')
into Loai (MaLoai, GioiTinh, TenLoai) values (N'ESAO006', 1, N'ÁO SƠ MI TAY DÀI')
into Loai (MaLoai, GioiTinh, TenLoai) values (N'ESAO007', 0, N'ÁO SƠ MI NGẮN TAY')
into Loai (MaLoai, GioiTinh, TenLoai) values (N'ESAO008', 1, N'ÁO SƠ MI NGẮN TAY')
into Loai (MaLoai, GioiTinh, TenLoai) values (N'ESAO009', 0, N'ÁO THUN DÀI TAY')
into Loai (MaLoai, GioiTinh, TenLoai) values (N'ESAO010', 1, N'ÁO THUN DÀI TAY')
into Loai (MaLoai, GioiTinh, TenLoai) values (N'ESAO011', 0, N'ÁO THUN NGẮN TAY')
into Loai (MaLoai, GioiTinh, TenLoai) values (N'ESAO012', 1, N'ÁO THUN NGẮN TAY')
into Loai (MaLoai, GioiTinh, TenLoai) values (N'ESAO013', 0, N'ÁO THUN BA LỖ')
into Loai (MaLoai, GioiTinh, TenLoai) values (N'ESAO014', 1, N'ÁO THUN BA LỖ')

into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (7, N'ÁO SƠ MI NAM DÀI TAY TRẮNG SMT16', N'ESAO001', N'so_mi_nam_16.jpg', 350000, 0.15, N'Sơ mi tay dài trắng phong cách tinh sảo', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (11, N'ÁO SƠ MI NAM DÀI TAY TRẮNG SMT12', N'ESAO001', N'so_mi_nam_012.jpg', 280000, 0.12, N'Sơ mi body hoa văn họa tiết tinh sảo', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (17, N'ÁO SƠ MI NAM DÀI TAY TRẮNG SMT12', N'ESAO001', N'so_mi_nam_01.jpg', 280000, 0, N'Sơ mi tay dài nam trắng phong cách', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (18, N'ÁO SƠ MI NAM DÀI TAY TRẮNG SMT0001', N'ESAO001', N'so_mi_nam_0001.jpg', 300000, 0.2, N'Áo sơ mi cổ cao trắng sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (19, N'ÁO SƠ MI NAM DÀI TAY SỌC ĐEN TRẮNG SMT0004', N'ESAO001', N'ao_so_mi_0004.jpg', 320000, 0.2, N'Áo sơ mi sọc đen trắng sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (20, N'ÁO SƠ MI NAM DÀI TAY ĐỎ SỌC SMT0006', N'ESAO001', N'ao_so_mi_0006.jpg', 300000, 0.2, N'Áo sơ mi cổ cao đỏ sọc sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (21, N'ÁO SƠ MI NAM DÀI TAY XÁM SỌC ĐEN SMT0018', N'ESAO001', N'ao_so_mi_0018.jpg', 300000, 0.2, N'Áo sơ mi cổ cao xám đen sọc sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (22, N'ÁO SƠ MI NAM DÀI TAY XANH SỌC ĐEN SMT0026', N'ESAO001', N'ao_so_mi_0026.jpg', 300000, 0.2, N'Áo sơ mi cổ cao xanh sọc sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (23, N'ÁO SƠ MI NAM NGẮN TAY SMT0001', N'ESAO007', N'ao_so_mi_0001.jpg', 300000, 0.2, N'Áo sơ mi cổ cao đỏ sọc sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (24, N'ÁO SƠ MI NAM NGẮN TAY HỌA TIẾT SMT0065', N'ESAO007', N'ao_so_mi_tay_ngan_0065.jpg', 300000, 0.2, N'Áo sơ mi ngắn xanh sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (25, N'ÁO SƠ MI NAM NGẮN TAY SMT0069', N'ESAO007', N'ao_so_mi_tay_ngan_0069.jpg', 300000, 0.2, N'Áo sơ mi ngắn xanh sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (26, N'ÁO THUN NAM NGẮN TAY SMT0005', N'ESAO011', N'ao_thun_nam_5.jpg', 110000, 0.2, N'Áo thun ngắn sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (27, N'ÁO THUN NAM NGẮN TAY SMT0001', N'ESAO011', N'ao_thun_nam_01.jpg', 110000, 0.2, N'Áo thun ngắn sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (28, N'ÁO THUN NAM NGẮN TAY SMT0010', N'ESAO011', N'ao_thun_nam_1.jpg', 110000, 0.2, N'Áo thun ngắn sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (29, N'ÁO THUN NAM NGẮN TAY SMT0041', N'ESAO011', N'ao_thun_nam_41.jpg', 110000, 0.2, N'Áo thun ngắn sang trọng quý phái', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) values (30, N'ÁO THUN NAM NGẮN TAY SMT0073', N'ESAO011', N'ao_thun_nam_73.jpg', 110000, 0.2, N'Áo thun ngắn sang trọng quý phái', N'ESHOP')

into TrangThai (MaTrangThai, TenTrangThai) values (0, N'Chờ xử lý')
into TrangThai (MaTrangThai, TenTrangThai) values (1, N'Đã xử lý')

into HoaDon (MaHD, MaKH, NgayDat, NgayGiao, HoTen, DiaChi, SDT_nguoinhan, GhiChu, PhiVanChuyen, MaTrangThai, MaNV, TongTienHang, TongThucThu) values (3, 5, TO_TIMESTAMP ('2018-11-30 17:53:28.673','YYYY-MM-DD HH24:MI:SS.FF3') , NULL, N'Nguyễn Thanh Sang', N'Chánh Mỹ, Bình Dương', N'0971890712', N'Giao hàng đến văn phòng khu phố', 35000, 1, NULL, NULL, NULL)
into HoaDon (MaHD, MaKH, NgayDat, NgayGiao, HoTen, DiaChi, SDT_nguoinhan, GhiChu, PhiVanChuyen, MaTrangThai, MaNV, TongTienHang, TongThucThu) values (4, 4, TO_TIMESTAMP ('2018-11-30 19:20:53.203','YYYY-MM-DD HH24:MI:SS.FF3') , NULL, N'Nguyễn Thành Long', N'Chánh Mỹ, Bình Dương', N'0971890712', N'Giao hàng đến văn phòng khu phố', 35000, 1, NULL, NULL, NULL)
into HoaDon (MaHD, MaKH, NgayDat, NgayGiao, HoTen, DiaChi, SDT_nguoinhan, GhiChu, PhiVanChuyen, MaTrangThai, MaNV, TongTienHang, TongThucThu) values (5, 4, TO_TIMESTAMP ('2018-12-01 21:08:24.610','YYYY-MM-DD HH24:MI:SS.FF3') , NULL, N'Nguyễn Thanh Sang', N'Chánh Mỹ, Bình Dương', N'0971890712', N'Giao hàng đến văn phòng khu phố', 35000, 1, NULL, NULL, NULL)
into HoaDon (MaHD, MaKH, NgayDat, NgayGiao, HoTen, DiaChi, SDT_nguoinhan, GhiChu, PhiVanChuyen, MaTrangThai, MaNV, TongTienHang, TongThucThu) values (6, 4, TO_TIMESTAMP ('2018-12-01 21:37:24.947','YYYY-MM-DD HH24:MI:SS.FF3') , NULL, N'Nguyễn Thành Long', N'Chánh Mỹ, Bình Dương', N'0971890712', N'Giao hàng đến văn phòng khu phố', 35000, 1, NULL, NULL, NULL)
into HoaDon (MaHD, MaKH, NgayDat, NgayGiao, HoTen, DiaChi, SDT_nguoinhan, GhiChu, PhiVanChuyen, MaTrangThai, MaNV, TongTienHang, TongThucThu) values (7, 6, TO_TIMESTAMP ('2018-12-01 21:40:56.943','YYYY-MM-DD HH24:MI:SS.FF3') , NULL, N'Nguyễn Thành Long', N'Chánh Mỹ, Bình Dương', N'0971890712', N'Giao hàng đến văn phòng khu phố', 35000, 1, NULL, NULL, NULL)
into HoaDon (MaHD, MaKH, NgayDat, NgayGiao, HoTen, DiaChi, SDT_nguoinhan, GhiChu, PhiVanChuyen, MaTrangThai, MaNV, TongTienHang, TongThucThu) values (8, 4, TO_TIMESTAMP ('2018-12-01 21:45:14.087','YYYY-MM-DD HH24:MI:SS.FF3') , NULL, N'Nguyễn Thanh Sang', N'Chánh Mỹ, Bình Dương', N'0971890712', N'Giao hàng đến văn phòng khu phố', 35000, 1, NULL, NULL, NULL)
into HoaDon (MaHD, MaKH, NgayDat, NgayGiao, HoTen, DiaChi, SDT_nguoinhan, GhiChu, PhiVanChuyen, MaTrangThai, MaNV, TongTienHang, TongThucThu) values (10, 4, TO_TIMESTAMP ('2018-12-01 22:07:14.300','YYYY-MM-DD HH24:MI:SS.FF3') , NULL, N'Nguyễn Thanh Sang', N'Chánh Mỹ, Bình Dương', N'0971890712', N'Giao hàng đến văn phòng khu phố', 35000, 0, NULL, NULL, NULL)
into HoaDon (MaHD, MaKH, NgayDat, NgayGiao, HoTen, DiaChi, SDT_nguoinhan, GhiChu, PhiVanChuyen, MaTrangThai, MaNV, TongTienHang, TongThucThu) values (11, 4, TO_TIMESTAMP ('2018-12-01 22:10:41.587','YYYY-MM-DD HH24:MI:SS.FF3') , NULL, N'Nguyễn Thành Long', N'Chánh Mỹ, Bình Dương', N'0971890712', N'Giao hàng đến văn phòng khu phố', 35000, 0, NULL, NULL, NULL)
into HoaDon (MaHD, MaKH, NgayDat, NgayGiao, HoTen, DiaChi, SDT_nguoinhan, GhiChu, PhiVanChuyen, MaTrangThai, MaNV, TongTienHang, TongThucThu) values (19, 4, TO_TIMESTAMP ('2018-12-04 11:34:00.213','YYYY-MM-DD HH24:MI:SS.FF3') , NULL, N'Nguyễn Thành Long', N'Chánh Mỹ, Bình Dương', N'0971890712', N'Giao hàng đến văn phòng khu phố', 35000, 0, NULL, NULL, NULL)
into HoaDon (MaHD, MaKH, NgayDat, NgayGiao, HoTen, DiaChi, SDT_nguoinhan, GhiChu, PhiVanChuyen, MaTrangThai, MaNV, TongTienHang, TongThucThu) values (20, 4, TO_TIMESTAMP ('2018-12-20 13:50:15.093','YYYY-MM-DD HH24:MI:SS.FF3') , NULL, N'Nguyễn Thanh Sang', N'Chánh Mỹ, Bình Dương', N'0971890712', N'Giao hàng đến văn phòng khu phố', 35000, 0, NULL, 1248000, 1158200)
into HoaDon (MaHD, MaKH, NgayDat, NgayGiao, HoTen, DiaChi, SDT_nguoinhan, GhiChu, PhiVanChuyen, MaTrangThai, MaNV, TongTienHang, TongThucThu) values (22, 11, TO_TIMESTAMP ('2018-12-20 21:57:30.273','YYYY-MM-DD HH24:MI:SS.FF3') , NULL, N'Đỗ Phúc Hậu', N'280 ADV', N'0904877306', NULL, 35000, 0, NULL, 297500, 332500)

into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values (1, 3, 20, 300000, 0.2, 2, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values (2, 3, 20, 300000, 0.2, 1, N'S')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values (3, 3, 24, 300000, 0.2, 2, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (4, 4, 7, 350000, 0.15, 3, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (5, 4, 20, 300000, 0.2, 2, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (6, 5, 26, 110000, 0.2, 2, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (7, 5, 25, 300000, 0.2, 1, N'S')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (8, 5, 20, 300000, 0.2, 2, N'L')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (9, 6, 19, 320000, 0.2, 2, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (10, 6, 21, 300000, 0.2, 3, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (11, 7, 7, 350000, 0.15, 2, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (12, 7, 22, 300000, 0.2, 2, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (13, 8, 19, 320000, 0.2, 1, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (14, 8, 20, 300000, 0.2, 1, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (17, 10, 21, 300000, 0.2, 2, N'S')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (18, 10, 22, 300000, 0.2, 1, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (19, 11, 20, 300000, 0.2, 2, N'S')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (20, 11, 20, 300000, 0.2, 1, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (29, 19, 7, 350000, 0.15, 3, N'S')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (30, 20, 20, 300000, 0.2, 2, N'S')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (31, 20, 19, 320000, 0.2, 3, N'M')
into ChiTietHD (MaCT, MaHD, MaHH, DonGia, GiamGia, SoLuong, KichCo) values  (32, 22, 7, 350000, 0.15, 1, N'S')
SELECT * FROM dual;

insert all
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (31, N'DAM NU 0006R', N'ESAO006', N'damnu_red.jpg', 300000, 0.05, N'ĐẦM NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (32, N'DAM NU 0006B', N'ESAO006', N'damnu_blue.jpg', 300000, 0.05, N'ĐẦM NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (33, N'DAM NU 0006Y', N'ESAO006', N'damnu_yellow.jpg', 300000, 0.05, N'ĐẦM NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (34, N'DAM NU 0006W', N'ESAO006', N'damnu_white.jpg', 300000, 0.05, N'ĐẦM NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (35, N'DAM NU 0006B1', N'ESAO006', N'damnu_blue1.jpg', 300000, 0.05, N'ĐẦM NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (36, N'DAM NU 0006PK', N'ESAO006', N'damnu_pink.jpg', 300000, 0.05, N'ĐẦM NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (37, N'DAM NU 0006LB', N'ESAO006', N'damnu_lightblue.jpg', 300000, 0.05, N'ĐẦM NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (38, N'DAM NU 0006BL', N'ESAO006', N'damnu_black.jpg', 300000, 0.05, N'ĐẦM NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (39, N'DAM NU 0006FS', N'ESAO006', N'damnu_freestyle.jpg', 300000, 0.05, N'ĐẦM NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (40, N'DAM NU 0006FS1', N'ESAO006', N'damnu_freestyle1.jpg', 300000, 0.05, N'ĐẦM NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (41, N'DAM NU 0006VJ', N'ESAO006', N'chanvay_jean.jpg', 300000, 0.05, N'CHÂN VÁY NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (42, N'CHAN VAY 0006VCR', N'ESAO008', N'chanvay_cream.jpg', 300000, 0.05, N'CHÂN VÁY NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (43, N'CHAN VAY 0006VBL', N'ESAO008', N'chanvay_black.jpg', 300000, 0.05, N'CHÂN VÁY NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (44, N'CHAN VAY 0006VW', N'ESAO008', N'chanvay_white.jpg', 300000, 0.05, N'CHÂN VÁY NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (45, N'CHAN VAY 0006VCR', N'ESAO008', N'chanvay_caro.jpg', 300000, 0.05, N'CHÂN VÁY NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (46, N'CHAN VAY 0006VCR', N'ESAO008', N'chanvay_caro1.jpg', 300000, 0.05, N'CHÂN VÁY NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (47, N'CHAN VAY 0006VFS', N'ESAO008', N'chanvay_freestyle.jpg', 300000, 0.05, N'CHÂN VÁY NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (48, N'CHAN VAY 0006VFS1', N'ESAO008', N'chanvay_freestyle1.jpg', 300000, 0.05, N'CHÂN VÁY NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (49, N'AO KIEU 0006A1', N'ESAO006', N'aokieu_1.jpg', 300000, 0.05, N'ÁO KIỂU NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (50, N'AO KIEU 0006A1', N'ESAO010', N'aokieu_1.jpg', 300000, 0.05, N'ÁO KIỂU NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (51, N'AO KIEU 0006A2', N'ESAO010', N'aokieu_2.jpg', 300000, 0.05, N'ÁO KIỂU NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (52, N'AO KIEU 0006A3', N'ESAO010', N'aokieu_3.jpg', 300000, 0.05, N'ÁO KIỂU NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (53, N'AO KIEU 0006A4', N'ESAO010', N'aokieu_4.jpg', 300000, 0.05, N'ÁO KIỂU NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (54, N'AO KIEU 0006A5', N'ESAO010', N'aokieu_5.jpg', 300000, 0.05, N'ÁO KIỂU NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (55, N'AO KIEU 0006A6', N'ESAO010', N'aokieu_6.jpg', 300000, 0.05, N'ÁO KIỂU NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (56, N'AO KIEU 0006A7', N'ESAO010', N'aokieu_7.jpg', 300000, 0.05, N'ÁO KIỂU NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (57, N'QUAN SHORT 0006Q1', N'ESAO012', N'quanshort_1.jpg', 300000, 0.05, N'QUẦN SHORT NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (58, N'QUAN SHORT 0006Q2', N'ESAO012', N'quanshort_2.jpg', 300000, 0.05, N'QUẦN SHORT NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (59, N'QUAN SHORT 0006Q3', N'ESAO012', N'quanshort_3.jpg', 300000, 0.05, N'QUẦN SHORT NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (60, N'QUAN SHORT 0006Q4', N'ESAO012', N'quanshort_4.jpg', 300000, 0.05, N'QUẦN SHORT NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (61, N'QUAN SHORT 0006Q5', N'ESAO012', N'quanshort_5.jpg', 300000, 0.05, N'QUẦN SHORT NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (62, N'QUAN SHORT 0006Q6', N'ESAO012', N'quanshort_6.jpg', 300000, 0.05, N'QUẦN SHORT NỮ ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (63, N'AO THUN 0006Q1', N'ESAO009', N'aothun_1.jpg', 300000, 0.05, N'ÁO THUN NAM ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (64, N'AO THUN 0006Q2', N'ESAO009', N'aothun_2.jpg', 300000, 0.05, N'ÁO THUN NAM ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (65, N'AO THUN 0006Q3', N'ESAO009', N'aothun_3.jpg', 300000, 0.05, N'ÁO THUN NAM ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (66, N'AO THUN 0006Q4', N'ESAO009', N'aothun_4.jpg', 300000, 0.05, N'ÁO THUN NAM ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (67, N'AO THUN 0006Q5', N'ESAO009', N'aothun_5.jpg', 300000, 0.05, N'ÁO THUN NAM ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (68, N'AO THUN 0006Q1', N'ESAO013', N'aothunbalo_1.jpg', 200000, 0.1, N'ÁO THUN NAM ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (69, N'AO THUN 0006Q2', N'ESAO013', N'aothunbalo_2.jpg', 200000, 0.1, N'ÁO THUN NAM ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (70, N'AO THUN 0006Q3', N'ESAO013', N'aothunbalo_3.jpg', 200000, 0.1, N'ÁO THUN NAM ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (71, N'AO THUN 0006Q4', N'ESAO013', N'aothunbalo_4.jpg', 200000, 0.1, N'ÁO THUN NAM ĐẸP SANG TRỌNG', N'ESHOP')
into HangHoa (MaHH, TenHH, MaLoai, Hinh, DonGia, GiamGia, MoTa, MaNCC) VALUES (72, N'AO THUN 0006Q5', N'ESAO013', N'aothunbalo_5.jpg', 200000, 0.1, N'ÁO THUN NAM ĐẸP SANG TRỌNG', N'ESHOP')

into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (1, 7, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (2, 7, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (3, 7, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (4, 11, N'S', 2)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (5, 11, N'M', 3)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (6, 11, N'L', 0)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (7, 17, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (8, 17, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (9, 17, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (10, 18, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (11, 18, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (12, 18, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (13, 19, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (14, 19, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (15, 19, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (16, 20, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (17, 20, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (18, 20, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (19, 21, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (20, 21, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (21, 21, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (22, 22, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (23, 22, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (24, 22, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (25, 23, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (26, 23, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (27, 23, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (28, 24, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (29, 24, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (30, 24, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (31, 25, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (32, 25, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (33, 25, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (34, 26, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (35, 26, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (36, 26, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (37, 27, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (38, 27, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (39, 27, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (40, 28, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (41, 28, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (42, 28, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (43, 29, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (44, 29, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (45, 29, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (46, 30, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (47, 30, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (48, 30, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (49, 31, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (50, 31, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (51, 31, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (52, 32, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (53, 32, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (54, 32, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (55, 33, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (56, 33, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (57, 33, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (58, 34, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (59, 34, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (60, 34, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (61, 35, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (62, 35, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (63, 35, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (64, 36, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (65, 36, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (66, 36, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (67, 37, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (68, 37, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (69, 37, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (70, 38, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (71, 38, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (72, 38, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (73, 39, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (74, 39, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (75, 39, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (76, 40, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (77, 40, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (78, 40, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (79, 41, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (80, 41, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (81, 41, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (82, 42, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (83, 42, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (84, 42, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (85, 43, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (86, 43, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (87, 43, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (88, 44, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (95, 44, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (96, 44, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (97, 45, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (98, 45, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (99, 45, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (100, 46, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (101, 46, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (102, 46, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (103, 47, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (104, 47, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (105, 47, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (106, 48, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (107, 48, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (108, 48, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (109, 49, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (110, 49, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (111, 49, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (112, 50, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (113, 50, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (114, 50, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (115, 51, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (116, 51, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (117, 51, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (118, 52, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (119, 52, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (120, 53, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (121, 54, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (122, 54, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (123, 54, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (124, 55, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (125, 55, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (126, 55, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (127, 56, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (128, 56, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (129, 56, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (130, 57, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (131, 57, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (132, 57, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (133, 58, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (134, 58, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (135, 58, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (136, 59, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (137, 59, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (138, 59, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (139, 60, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (140, 60, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (141, 60, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (142, 61, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (143, 61, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (144, 61, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (145, 62, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (146, 62, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (147, 62, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (148, 63, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (149, 63, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (150, 63, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (151, 64, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (152, 64, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (153, 64, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (154, 65, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (155, 65, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (156, 65, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (157, 66, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (158, 66, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (159, 66, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (160, 67, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (161, 67, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (162, 67, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (163, 68, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (164, 68, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (165, 68, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (166, 69, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (167, 69, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (168, 69, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (169, 70, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (170, 70, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (171, 70, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (172, 71, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (173, 71, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (174, 71, N'S', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (175, 72, N'M', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (176, 72, N'L', 50)
into SanPhamKho (MaSP_Kho, MaHH, KichCo, SoLuong) VALUES (177, 72, N'S', 50)
SELECT * FROM dual;

COMMIT;

